### ISSUE TITLE
[Health Introspection] Add deep health introspection support

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#1087]
## Problem
Today, 3rd-party node services offer (very) shallow health checks for node deployments through the metric ports. However, in the world of incentivized node operation we need to be able to perform deeper state introspection, including:
- Enforcing SLAs (uptime, latency, throughput, etc.)
- Ensuring network connectivity and responsiveness
- Verifying data availability and integrity
- Onboarding and debugging (e.g., verifying deployments before coming online)

## Solution
Build tooling that will allow us to communicate with node microservices directly without having to run a node, e.g., a client-side tool that handles the noise protocol/handshake:
- The tool could then be run by operators who are onboarding to verify the correctness of their deployment
- Community members could even use this tool to build front-end node testers (e.g., the websites we see today)
- The tool could also be used in our testing environments (smoke tests!!) to improve our end-to-end test harnesses. We have limited options when it comes to state inspection.

## Tasks
(These are not in order of priority. Optional "nice to have" features are marked 😄)
- [ ] Build an official node checking frontend (e.g., website)
- [ ] Build client side tooling to connect with a node and make requests
- [ ] Integrate the official node checking frontend with this tooling to begin to offer deeper health introspections with a nice UI
- [ ] Build tooling to support verification commands that check everything we (or an operator) might want to know about the health of their node
- [ ] (Optional) Build automated tooling to continuously inspect and monitor the health of nodes in the network, e.g., inspection-style nodes.
