### ISSUE TITLE
[Feature Request][compiler-v2] Tracking various potential compiler optimizations that we may want to implement

### ISSUE THREAD

**Issue by vineethk** [aptos-labs/aptos-core#13571]
# 🚀 Feature Request

List of compiler optimizations that may be worth implementing for the complier v2:
- [ ] Loop invariant code motion
- [ ] Common sub-expression elimination, global value numbering
- [ ] Constant propagation and folding
- [ ] Loop fusion
- [ ] Super-optimization for loop-free sequence of instructions

When we decide to implement any of these optimizations, we can check them off this list and create individual issues to track the ones selected.

**Comment by GotenJBZ** [comment]
[ ] Avoid unnecessary bytecodes for casted if/else expressions

`(if c { a } else { b }) as T` currently emits an extra temporary local:

```
st_loc tmp   // in each branch
move_loc tmp // after the if/else
```
`if (c) { a as T } else { b as T }` produces equivalent semantics while removing the extra `st_loc / move_loc` pair.
