### ISSUE TITLE
[Feature Request] `pre-commit` support for CLI

### ISSUE THREAD

**Issue by alnoki** [aptos-labs/aptos-core#14789]
# Todo

cc @banool @chen-robert @xbtmatt @crbl69 @wrwg 

- [ ] Add `pre-commit` hook for `aptos`
- [ ] Add support for testing (e.g. assert all tests pass)
- [ ] Add support for coverage (e.g. assert a certain percentage)
- [ ] Add support for formatting (related https://github.com/movebit/movefmt/issues/39)
- [ ] Auto-discovery for multiple packages in a repo
- [ ] Ability to exclude certain packages

## Motivation/pitch

This tooling will make it easier for ecosystem to develop safe code

## Additional context

Something like the config I currently have for Rust,which can do `fmt`, `cargo check`, and `clippy` all from the same `pre-commit` hook:

```yaml
-
  hooks:
  -
    args:
    - '--manifest-path'
    - 'src/rust/Cargo.toml'
    - '-p'
    - 'allowlister3000'
    - 'broker'
    - '--'
    id: 'fmt'
  -
    args:
    - '--manifest-path'
    - 'src/rust/Cargo.toml'
    - '--'
    id: 'cargo-check'
  -
    args:
    - '--manifest-path'
    - 'src/rust/Cargo.toml'
    - '--'
    - '--deny'
    - 'clippy::all'
    id: 'clippy'
  repo: 'https://github.com/doublify/pre-commit-rust'
  rev: 'v1.0'
```

**Comment by banool** [comment]
So you imagine the CLI spits out a template for pre-commit to consume or something?

I feel like some of this functionality could be facilitated more easily in conjunction with a more powerful package manager, e.g. imagine scripts in package.json, the special cased "prepare" script, cargo-like / pnpm-like workspaces, etc.

Then to really bring it all together, some GitHub actions for running testing, linting, formatting, etc.

Just throwing out some additional ideas, really piling on 😛

**Comment by alnoki** [comment]
> a template for pre-commit to consume or something?

Not exactly, the `yaml` file I provided above is an example of `pre-commit` hook for Rust. Ideally there would be an `aptos` `pre-commit` hook fo the similar form

> Then to really bring it all together, some GitHub actions for running testing, linting, formatting, etc.

This is accomplished by simply adding the `pre-commit` hook support I suggest, because then someone just has to add another hook to their config

**Comment by alnoki** [comment]
@vineethk per today's Move interest group discussion I've updated the above description to include `aptos move lint`
