### ISSUE TITLE
Tracking Issue for Gas Metering & Native Functions

### ISSUE THREAD

**Issue by vgao1996** [aptos-labs/aptos-core#2463]
## P0 - Launch Blocking
- [x] [Aptos] Base PR (https://github.com/aptos-labs/aptos-core/pull/2358)
- [x] [Aptos] Fix the scaling factor
- [x] [Aptos] Gas parameters for storage operations
  - [x] https://github.com/aptos-labs/aptos-core/pull/3021
- [x] [Aptos] Determine the initial values of the gas parameters
  - [x] [Aptos] Set min_price_per_gas_unit to something > 0 in the genesis 
- [x] [Aptos/Move] Gas parameters for table
  - https://github.com/aptos-labs/aptos-core/pull/3250
- [x] [Move] Revisit abstract memory size calculation
  - [x] https://github.com/move-language/move/pull/387
  - [x] https://github.com/aptos-labs/aptos-core/pull/3094
  - [x] https://github.com/move-language/move/pull/388
  - [x] https://github.com/aptos-labs/aptos-core/pull/3171
  - [x] https://github.com/aptos-labs/aptos-core/pull/3274
- [x] [Aptos] Charge for txn parameters -- shouldn't be a problem since we charge intrinsic gas
- [x] [Aptos/Move] Charge for writes by change set
  - Should cover code publishing & upgrading
  - [x] https://github.com/move-language/move/pull/373
  - [x] https://github.com/aptos-labs/aptos-core/pull/3069
  - [x] Aptos PR

## P1 - Nasty Issues That May Have Work-arounds
- [x] [Aptos/Move] Feature unification problems: unit test natives in prod
- [x] [Aptos/Move] Safe gas algebra 
  - [x] https://github.com/move-language/move/pull/383
  - [x] https://github.com/aptos-labs/aptos-core/pull/3094
- [x] ~~[Move] Should charge for the whole transitive closure when loading modules~~ Won't fix in the short term
- [x] [Move] Verification may be non-linear
  - [x] https://github.com/move-language/move/pull/369
  - [x] https://github.com/aptos-labs/aptos-core/pull/3019
- [x] [Aptos] Refactor sip_hash

## P2 - Good to have
- [x] [Aptos] Documentation for the new gas meter (https://github.com/aptos-labs/aptos-core/pull/2696)
- [ ] [Aptos] Should check if the gas schedule is consistent when updating
- [ ] [Aptos/Move] get module/resource size without loading
- [ ] [Aptos] Add more tests (for everything)

## Other
- [ ] [Aptos] Default gas parameters for the APIs
- [x] [Aptos] Gas metering for aggregator natives

**Comment by vgao1996** [comment]
@wrwg this is the list of gas issues/tasks I mentioned
