### ISSUE TITLE
[tooling] CLI tooling for Framework / Move

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#416]
### Goals
* Works on any Aptos chain network (devnet, local testnet, etc.)
* Enables developers to build on Aptos easily
* Remove multiple tools that exist now into one tool
* Allow for automation around CLI

### Requirements
* JSON Output -> (Allow automation)
* Local configuration -> (.aptos/ folder for CLI configuration)
* Move code input -> No precompiled binaries to be passed in

### Tasks

- [ ] Build framework to have varying inputs to CLI with clap
- [ ] Build test framework for CLI
- [ ] Build support for listing resources under an account
- [ ] Build support to publish packages (including modules) to an account
- [ ] Build support to compile, verify, and test move packages
- [ ] Build support to call mutable move functions -> function to transaction mapping
- [ ] Build support for testing move code with logs and printing
- [ ] Build support for error mapping of error codes in move

### Nice to haves

- [ ] CLI autocompletion with clap
- [ ] CLI logging
- [ ] CLI wildcard support (including in Windows)
- [ ] CLI support in windows
- [ ] Snapshot creation and loading
- [ ] Testing arbitrary state via Move
- [ ]
