### ISSUE TITLE
[Network Monitoring Service] Supporting topology awareness

### ISSUE THREAD

**Issue by JoshLind** [aptos-labs/aptos-core#696]
## Problem
Today, we have no information about the topology of our network besides IP addresses from telemetry data. This means:
- Mempool cannot efficiently identify how to forward transactions to the validators, leading to cycles and unnecessary network contention.
- Polling in the Aptos Data Client is dumb (e.g., round robin). It would be better to poll known "upstream" peers more frequently as they should have data sooner.
- We have no way of knowing what peers exist in the network and how they are connected.
- State sync cannot prioritize which peers to subscribe to.
- Peer scoring exists in the Aptos Data Client, but if a peer is misbehaving, we cannot disconnect from it without knowing other peers to connect to.

## Solution
Create a new network monitoring service that allows clients to fetch: (i) current depth from the validators (e.g., number of hops); (ii) all connected peers; (iii) all known peers (including transitively known); (iv) the addresses of the current validator set and the validator fullnode set; (v) peer scores; and (vi) anything else we deem useful. Nodes can use this service to build a better understanding of their peers and make smarter decisions at the application level.

Note: by building this as a microservice, we can better enhance our testing infrastructure. 

## Tasks
(These are not in order of priority. Optional "nice to have" features are marked 😄)
- [ ] Implement a basic network service skeleton.
- [ ] Plug the service into Aptos Node (so that clients can access the service over AptosNet).
- [ ] Implement a basic client poller that periodically pings peers for network information.
- [ ] Implement the various APIs (as described above), e.g., fetch all known peers, validators, vfns, etc. Make data available to each network service via the network interface (e.g., through the peer metadata storage).
- [ ] (Optional) Merge the client poller with the health service such that if peers fail to respond to network service pings, the peer is considered offline.
- [ ] (Optional) Deprecate and remove the health service.
- [ ] Implement latency polls, such that peer pings are periodically measured for network latency. Expose this data to each node via the peer metadata storage.
- [ ] Update state sync to use peer topology information to make better decisions about requesting data.
- [ ] Update mempool to use peer topology information to make better decisions about forwarding transactions.
- [ ] (Optional) Update the network peer manager to handle "disconnection" notifications (i.e., each application can notify the peer manager that a given peer is behaving badly and should be replaced).
- [ ] ...
