### ISSUE TITLE
[network] Make NetworkAddress canonical and easier to use

### ISSUE THREAD

**Issue by gregnazario** [aptos-labs/aptos-core#864]
## Problem

Right now the [NetworkAddress](https://github.com/aptos-labs/aptos-core/blob/main/types/src/network_address/mod.rs) struct is very confusing to anyone who uses it.  It's composed of a set of unordered protocols that make an address, though this can make it confusing, and not easy to build.

## Tasks
- [ ] Make NetworkAddress canonical (e.g. Always `/<IP or DNS>/<ip or name>/<TCP or otherwise>/<port>/ln-noise-ix/<public_key>/ln-handshake/0`)
- [ ] Fix `ln` prefix of fields to be better than just `ln` or drop the `ln` which used to stand for `libra-net`
- [ ] Make straight forward parsing to get keys
- [ ] Should we prevent duplicate keys & types? e.g. no DNS and IP or two keys (unless that's how we'll support multiple keys)
- [ ] Add first class support for canonical changes
- [ ] Add ability in tooling to validate an address
- [ ] Add support to easily add other protocols in place of TCP e.g. UDP
- [ ] Use an enum for the handshake protocol so it isn't just a hardcoded number

## Goals
* Ensure that it's easy for users to understand
* Ensure consistency among types
* Increase ease of parsing across languages
* Make it straight forward for handshake and address upgrading

**Comment by gregnazario** [comment]
@Markuze This should be a good start for you and getting  Rust in general.  Once we're done with this we can talk some more on the stuff that comes after.

**Comment by oxlime** [comment]
Is this currently open?

**Comment by banool** [comment]
While we're at it, how about just `noise` instead of `noise-ix`. Or if we want to keep it, expand it into something that means something for the uninitiated.

**Comment by Markuze** [comment]
commit 4ce85456853c7b19b0a751fb645abd2971cc4c0c
Author: Alex Markuze <alex@Alexs-MacBook-Pro.local>
Date:   Sun May 22 21:42:31 2022 +0300

    [types/network] Enforce canonical format for NetworkAddresses
    
    Enforcing a canonical structure for struct NetworkAddresses.
    The following oredring is enforced:
    
    1. Network - ipX/DNS/Memory
    2. Transpot - TCP
    3. Session - Noise
    4. Presentation - Handshake
    
    Closes: #1182
